version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - '80:80'
      - '443:443'  # For future HTTPS support
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # Uncomment when you add SSL certificates
    depends_on:
      - terminalx
      - sftp-browser
    restart: unless-stopped
    networks:
      - webapp_network

  terminalx:
    image: terminalx:1.1.3.2d
    container_name: terminalx
    # Keep original port exposure for direct access + DNS access via nginx
    ports:
      - '8087:8087'
    restart: unless-stopped
    # If you need to mount local config, uncomment & adjust:
    #volumes:
    #   - ./config.json:/app/config.json:ro
    #   - ./static:/app/static:ro
    #   - ./templates:/app/templates:ro
    environment:
      - TD_PATH=/sources/indot.html
      - MOBY_PORT=9085
      # SFTP Configuration
      - SFTP_HOST=                    # Leave empty to use current hostname (recommended)
      - SFTP_PORT=3000               # Port where sftp-browser service runs
      - SFTP_PROTOCOL=http           # Force HTTP to avoid SSL errors
      # Token minting secret used to encrypt SFTP tokens (must match sftp-browser)
      - TOKEN_SECRET=your_very_secure_random_secret_key_here_change_me_12345
      # Optional: max TTL the TerminalX side will mint (seconds)
      - TOKEN_TTL_SECONDS=120
      # Dynamic session secret (optional - will auto-generate if not set)
      # - SESSION_SECRET=another_random_secret_for_sessions_67890
    networks:
      - webapp_network
      
  sftp-browser:
    image: sftp-server:1.0.2.1
    container_name: sftp-server
    # Keep original port exposure for direct access + DNS access via nginx
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      # Must match terminalx TOKEN_SECRET for decryption
      - TOKEN_SECRET=your_very_secure_random_secret_key_here_change_me_12345
      # Optional: server-side TTL enforcement (seconds)
      - TOKEN_MAX_TTL_SECONDS=300
      # Optional: session timeout for idle SFTP connections (ms)
      - SESSION_TIMEOUT=600000
    #volumes:
    #   - ./web:/app/web:ro
    networks:
      - webapp_network

networks:
  webapp_network:
    driver: bridge